# Uncomment this line to define a global platform for your project
platform :ios, '13.0'
# Uncomment this line if you're using Swift


use_frameworks!

target 'Demo' do

end

target 'DemoTests' do

pod 'NSObject+Combine', :path => '../'

pod 'Quick'
pod 'Nimble'

end

